# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.1.0"

# Hanami 2.x framework
gem "hanami", "~> 2.2"
gem "hanami-controller", "~> 2.2"
gem "hanami-router", "~> 2.2"
gem "hanami-view", "~> 2.2"

# Rodauth authentication
gem "rodauth-rack", path: "../.."
gem "tilt", "~> 2.4"

# Database
gem "sequel", "~> 5.85"
gem "sqlite3", "~> 2.4"

# Password hashing
gem "bcrypt", "~> 3.1"

# Web server
gem "puma", "~> 6.4"

group :development do
  gem "hanami-webconsole", "~> 2.2"
end

group :development, :test do
  gem "dotenv", "~> 3.1"
end
